name: flutter_firebase_chat_core
description: >
  Actively maintained, community-driven Firebase BaaS for chat applications
  with an optional chat UI.
version: 1.1.0
homepage: https://flyer.chat
repository: https://github.com/flyerhq/flutter_firebase_chat_core

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  flutter_chat_types: ^2.2.0
  meta: ^1.3.0

dependency_overrides:
  flutter_chat_types:
    git:
      url: https://github.com/wevertoonsilva/flutter_chat_types

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0
